template = "https://github.com/giellalt/template-lang-und"
rev_id = 279
template_sha = "7e1364a63ae8dd7a44d168dead7dc395b65c35a3"

[replacements]
__GLOTTOLOG_ID__ = "cent2128"
__REPO__ = "lang-ess"
__UND2C__ = "ess"
__UNDEFINED__ = "Central Siberian Yupik"
__UND__ = "ess"
